# Generated by Django 4.1.4 on 2023-01-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="JWTToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jwt_token", models.TextField(verbose_name="JWT Token")),
                (
                    "social_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialaccount.socialtoken",
                    ),
                ),
            ],
        ),
    ]
